### ISSUE TITLE
Glyphicons

### ISSUE THREAD

**Issue by tomasreigl** [rstudio/shinybootstrap2#1]
Hello,
shouldn't function icon() use also 'glyphicon' library?

**Comment by wch** [comment]
Ideally, it would also support glyphicon, but there's a good reason it doesn't. The purpose of shinybootstrap2 is for backward compatibility. That is, it allows code written for Shiny 0.10.2.2 and earlier to be used seamlessly with Shiny 0.11. Because of this, the code for `icon()` was taken straight from Shiny 0.10.2.2. That version of Shiny (and previous ones) didn't support glyphicon, which was probably an oversight.

If you're curious, here's the code from 0.10.2.2:
  https://github.com/rstudio/shiny/blob/v/0/10/2.2/R/bootstrap.R#L1768-L1823

If you really want to use glyphicon, I'd suggest moving to 0.11 (and Bootstrap 3) if possible, since that's what future versions of Shiny will use. If that's not feasible, you could write your own modified version of `icon()` that supports glyphicon.
